### ISSUE TITLE
Registration should not happen until subscribe

### ISSUE THREAD

**Issue by JakeWharton** [helmbold/rxfilewatcher#1]
Currently registration of directories happens in the constructor of `ObservableFactory`. This is incorrect as the observables being created are cold, not hot. Registration should be deferred until subscription happens.

**Comment by helmbold** [comment]
Thanks for your feedback. I'm wondering what would be the (best) way to implement that. Should this happen in the block beginning at line [60](https://github.com/helmbold/rxfilewatcher/blob/master/src/main/java/de/helmbold/rxfilewatcher/DirectoryObservable.java#L60)? Or should it be written in a  different way?

**Comment by JakeWharton** [comment]
Yep. That's pretty much the canonical place to do this work. The tree walking to register would happen first before the logic would move on to do the actual watching.

**Comment by helmbold** [comment]
Fixed: https://github.com/helmbold/rxfilewatcher/commit/8f148fcab0a85b1779b538e8ce6e699fa4d129c6 I hope it is now like it should be.
