### ISSUE TITLE
The FileSystem of the configured Path is not used

### ISSUE THREAD

**Issue by JakeWharton** [helmbold/rxfilewatcher#3]
A `Path` for a non-default `FileSystem` might be used for creation yet the created observables assumes it can watch from `FileSystems.getDefault()`. The `FileSystem` from the supplied `Path` should be used.

**Comment by helmbold** [comment]
Fixed: https://github.com/helmbold/rxfilewatcher/commit/fd9f96333b53a2a7c7173753e6c52418ebe6172e
