### ISSUE TITLE
Continuing after interruption/onError breaks Observable contract

### ISSUE THREAD

**Issue by JakeWharton** [helmbold/rxfilewatcher#4]
After `onError` is invoked, no events sent to `onNext` or `onComplete` will be sent downstream per the contract of `Observable` (and enforced by RxJava's `SafeSubscriber`). The loop should break, not continue if such an exception occurs.

**Comment by helmbold** [comment]
Fixed: https://github.com/helmbold/rxfilewatcher/commit/692663ef1cfede0f7f520f834a9ffa860956e19d
